import React from 'react'

export default function FeedbackPanel({ analysis, loading, onRequestAnalyze }) {
  const placeholder = {
    clarity: 0,
    tone: 'Neutral',
    impact: 0,
    suggestions: ['Write a clearer thesis sentence.', 'Add specific examples to support claims.']
  }

  const data = analysis ?? placeholder

  const clarityPercent = Math.max(0, Math.min(100, Number(data.clarity || 0)))
  const impactPercent = Math.max(0, Math.min(100, Number(data.impact || 0)))

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl shadow p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-semibold text-slate-800 dark:text-slate-100">AI Feedback</h3>
        <button
          onClick={onRequestAnalyze}
          className="text-xs px-2 py-1 rounded bg-slate-100 dark:bg-slate-700"
        >
          Re-analyze
        </button>
      </div>

      <div className="space-y-3">
        <div>
          <label className="text-xs text-slate-500 dark:text-slate-300">Clarity</label>
          <div className="w-full h-3 bg-slate-100 dark:bg-slate-700 rounded mt-1">
            <div style={{ width: `${clarityPercent}%` }} className="h-3 bg-emerald-400 rounded transition-all" />
          </div>
        </div>

        <div>
          <label className="text-xs text-slate-500 dark:text-slate-300">Impact</label>
          <div className="w-full h-3 bg-slate-100 dark:bg-slate-700 rounded mt-1">
            <div style={{ width: `${impactPercent}%` }} className="h-3 bg-indigo-500 rounded transition-all" />
          </div>
        </div>

        <div>
          <label className="text-xs text-slate-500 dark:text-slate-300">Tone</label>
          <div className="mt-1 text-sm font-medium text-slate-700 dark:text-slate-200">{data.tone}</div>
        </div>

        <div>
          <label className="text-xs text-slate-500 dark:text-slate-300">Top suggestions</label>
          <ul className="list-disc list-inside mt-2 text-sm text-slate-600 dark:text-slate-300">
            {(data.suggestions || []).slice(0, 4).map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ul>
        </div>

        <div className="text-xs text-slate-500 dark:text-slate-400">
          {loading ? 'Analyzing...' : 'Scores approximate and generated by demo backend.'}
        </div>
      </div>
    </div>
  )
}
